### ISSUE TITLE
Running giterm without git installed raises a Python exception

### ISSUE THREAD

**Issue by timlegrand** [timlegrand/giterm#7]
Running `giterm` without `git` installed raises a Python exception. See below:

```
Traceback (most recent call last):
 [...]/giterm/rungit.py", line 20, in run_with_error_code
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] Aucun fichier ou dossier de ce type
```

We'd prefer having an explicit message instead.

**Comment by timlegrand** [comment]
Done.
